sky_store/app_newsletter/urls.py
from django.urls import path

from .apps import AppNewsletterConfig
from .views import (
    ClientCreateView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
    NewsletterListView,
    NewsletterDetailView,
    NewsletterCreateView,
    NewsletterUpdateView,
    NewsletterDeleteView,
    NewsletterLogListView,
    NewsletterLogDetailView
)

app_name = AppNewsletterConfig.name

urlpatterns = [
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletter/update/<int:pk>/', NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletter/delete/<int:pk>/', NewsletterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletterlogs/', NewsletterLogListView.as_view(), name='newsletter_log_list'),
    path('newsletterlogs/<int:pk>/', NewsletterLogDetailView.as_view(), name='newsletter_log_detail'),
]

sky_store/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_catalog.urls', namespace='app_catalog')),
    path('', include('app_blog.urls', namespace='app_blog')),
    path('', include('app_newsletter.urls', namespace='app_newsletter')),
    path('user/', include('app_user.urls', namespace='app_user'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_store/app_newsletter/models.py
from django.db import models
from django.urls import reverse

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Модель, описывающая клиента
    """
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=100, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активный')

    class Meta:
        db_table = 'clients'
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('app_newsletter:client_detail', args=[str(self.id)])

    def make_inactive(self):
        """
        Делает клиента неактивным.
        """
        self.is_active = False
        self.save()


class Newsletter(models.Model):
    """
    Модель, описывающая рассылку
    """
    FREQUENCY_CHOICES = [
        ('D', 'Раз в день'),
        ('W', 'Раз в неделю'),
        ('M', 'Раз в месяц')
    ]

    STATUS_CHOICES = [
        ('F', 'Завершена'),
        ('C', 'Создана'),
        ('S', 'Запущена')
    ]

    time = models.TimeField(verbose_name='Время рассылки')
    frequency = models.CharField(max_length=1, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='Статус рассылки', blank=True)
    clients = models.ManyToManyField('Client', verbose_name='Клиенты', related_name='newsletters')
    messages = models.ManyToManyField('Message', verbose_name='Сообщения', related_name='newsletters')
    is_active = models.BooleanField(default=True, verbose_name='Активная')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    finish_date = models.DateField(verbose_name='Дата завершения рассылки')
    finish_time = models.TimeField(verbose_name='Время завершения рассылки')

    class Meta:
        db_table = 'newsletters'
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f"Рассылка #{self.pk}"

    def get_absolute_url(self):
        return reverse('app_newsletter:newsletter_detail', args=[str(self.pk)])

    def make_inactive(self):
        """
        Делает рассылку неактивной.
        """
        self.is_active = False
        self.save()


class Message(models.Model):
    """
    Модель, описывающая сообщение
    """
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')

    class Meta:
        db_table = 'messages'
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.subject


class NewsletterLog(models.Model):
    """
    Модель, описывающая лог рассылки
    """
    STATUS_CHOICES = [
        ('S', 'Success'),
        ('F', 'Failure')
    ]

    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='Статус')
    server_response = models.TextField(verbose_name='Ответ почтового сервера')
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, verbose_name='Клиент', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='Сообщение', **NULLABLE)
    newsletter = models.ForeignKey(Newsletter, on_delete=models.SET_NULL, verbose_name='Рассылка', **NULLABLE)

    class Meta:
        db_table = 'newsletter_logs'
        verbose_name = 'Лог отправки письма'
        verbose_name_plural = 'Логи отправок писем'

    def __str__(self):
        return f'Лог #{self.pk}'

sky_store/app_newsletter/forms.py
from django import forms

from .models import Client, Newsletter


class SelectMultipleWithAllOption(forms.SelectMultiple):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        option = super().create_option(name, value, label, selected, index, subindex=subindex, attrs=attrs)
        if value is None:
            option['attrs']['value'] = 'all'
            option['label'] = 'Выбрать все'
        return option


class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'first_name', 'last_name', 'middle_name']
        labels = {
            'email': 'Электронная почта',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'middle_name': 'Отчество (необязательно)'
        }
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Введите электронную почту'
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Введите имя'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Введите фамилию'
                }
            ),
            'middle_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Введите отчество'
                }
            )
        }


class NewsletterCreateForm(forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        label='Клиенты',
        widget=SelectMultipleWithAllOption(
            attrs={
                'class': 'form-control'
            }
        ),
    )

    class Meta:
        model = Newsletter
        fields = ['time', 'finish_date', 'finish_time', 'frequency', 'clients', 'messages']
        labels = {
            'time': 'Время',
            'finish_date': 'Дата завершения рассылки',
            'finish_time': 'Время завершения рассылки',
            'frequency': 'Периодичность',
            'status': 'Статус',
            'clients': 'Клиенты',
            'messages': 'Сообщения'
        }
        widgets = {
            'time': forms.TimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'time'
                }
            ),
            'finish_date': forms.TimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date'
                }
            ),
            'finish_time': forms.TimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'time'
                }
            ),
            'frequency': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'messages': forms.SelectMultiple(
                attrs={
                    'class': 'form-control'
                }
            )
        }

sky_store/app_newsletter/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from .forms import ClientCreateForm, NewsletterCreateForm
from .models import Client, Newsletter, NewsletterLog
from .services import NewsletterDeliveryService


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Создать'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Клиент успешно создан')
        return response


class ClientListView(ListView):
    model = Client
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True).order_by('first_name')
        return queryset


class ClientDetailView(DetailView):
    model = Client


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Редактировать'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Данные клиента успешно отредактированы')
        return response


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('app_newsletter:client_list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.make_inactive()

        message = f'Статус пользователя "{self.object}" изменён на неактивный'
        messages.success(request, message)

        return HttpResponseRedirect(self.get_success_url())


class NewsletterListView(ListView):
    model = Newsletter
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True).order_by('-created_at')
        return queryset


class NewsletterDetailView(DetailView):
    model = Newsletter


class NewsletterCreateView(CreateView):
    model = Newsletter
    form_class = NewsletterCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Создать'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        self.object.status = 'C'
        self.object.save()

        delivery_service = NewsletterDeliveryService(self.object)
        delivery_service.create_task()

        self.object.status = 'S'
        self.object.save()

        messages.success(self.request, 'Рассылка успешно создана')
        return response


class NewsletterUpdateView(UpdateView):
    model = Newsletter
    form_class = NewsletterCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Редактировать'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        delivery_service = NewsletterDeliveryService(self.object)
        delivery_service.delete_task()
        delivery_service.create_task()

        messages.success(self.request, 'Данные рассылки успешно отредактированы')
        return response


class NewsletterDeleteView(DeleteView):
    model = Newsletter
    success_url = reverse_lazy('app_newsletter:newsletter_list')

    def form_valid(self, form):
        self.object = self.get_object()

        delivery_service = NewsletterDeliveryService(self.object)
        delivery_service.delete_task()

        message = f'Рассылка "{self.object}" была удалена'
        self.object.delete()

        messages.success(self.request, message)

        return HttpResponseRedirect(self.get_success_url())


class NewsletterLogListView(ListView):
    model = NewsletterLog
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by('-date_time')
        return queryset


class NewsletterLogDetailView(DetailView):
    model = NewsletterLog

sky_store/app_newsletter/templates/app_newsletter/client_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить клиента
{% endblock %}

{% block header %}
    Удалить клиента
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <p>Уверены, что хотите удалить клиента "{{ object }}"?</p>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
    </form>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/client_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object }}
{% endblock %}

{% block header %}
    {{ object }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <p><b>Имя: </b>{{ object.first_name }}</p>
            <p><b>Фамилия: </b>{{ object.last_name }}</p>
            {% if object.middle_name %}
                <p><b>Отчество: </b>{{ object.last_name }}</p>
            {% endif %}
            <p><b>Электронная почта: </b>{{ object.email }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 d-flex justify-content-between">
            <div>
                <a href="{% url 'app_newsletter:client_update' pk=object.pk %}" class="btn btn-warning"
                   role="button">
                    Редактировать
                </a>
            </div>
            <div>
                <a href="{% url 'app_newsletter:client_delete' pk=object.pk %}" class="btn btn-danger"
                   role="button">
                    Удалить
                </a>
            </div>
        </div>
    </div>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/client_form.html
{% extends 'base.html' %}

{% block title %}
    {{ action }} клиента
{% endblock %}

{% block header %}
    {{ action }} клиента
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="{{ action }}">
    </form>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/client_list.html
{% extends 'base.html' %}

{% block title %}
    Список клиентов
{% endblock %}

{% block header %}
    Клиенты
{% endblock %}

{% block content %}
    {% if object_list %}
        <table class="table table-striped table-hover caption-top">
            <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Электронная почта</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Отчество</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.id }}</th>

                    <td>
                        <a href="{% url 'app_newsletter:client_detail' pk=object.pk %}">{{ object.email }}</a>
                    </td>
                    <td>{{ object.first_name }}</td>
                    <td>{{ object.last_name }}</td>
                    <td>
                        {% if object.middle_name %}
                            {{ object.middle_name }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'app_newsletter/includes/paginator.html' %}
    {% else %}
        <h3>Пока здесь пусто</h3>
    {% endif %}
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletter_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить рассылку
{% endblock %}

{% block header %}
    Удалить рассылку
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <p>Уверены, что хотите удалить рассылку "{{ object }}"?</p>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
    </form>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletter_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object }}
{% endblock %}

{% block header %}
    {{ object }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h5>Время:</h5>
            <p>{{ object.time }}</p>
            <h5>Периодичность:</h5>
            <p>{{ object.get_frequency_display }}</p>
            <h5>Статус:</h5>
            <p>{{ object.get_status_display }}</p>
            <h5>Сообщения в этой рассылке:</h5>
            <ul>
                {% for message in newsletter.messages.all %}
                    <li>
                        <p><b>{{ message.subject }}</b></p>
                        <p>{{ message.body }}</p>
                    </li>
                    {% empty %}
                    <li>В этой рассылке нет сообщений.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 d-flex justify-content-between">
            <div>
                <a href="{% url 'app_newsletter:newsletter_update' pk=object.pk %}" class="btn btn-warning"
                   role="button">
                    Редактировать
                </a>
            </div>
            <div>
                <a href="{% url 'app_newsletter:newsletter_delete' pk=object.pk %}" class="btn btn-danger"
                   role="button">
                    Удалить
                </a>
            </div>
        </div>
    </div>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletter_form.html
{% extends 'base.html' %}

{% block title %}
    {{ action }} рассылку
{% endblock %}

{% block header %}
    {{ action }} рассылку
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="{{ action }}">
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_clients').prepend('<option value="all">Выбрать все</option>');

            $('#id_clients').on('click', function (e) {
                if ($(e.target).val() == 'all') {
                    e.preventDefault();
                    $(this).find('option').prop('selected', $(e.target).prop('selected'));
                    $(e.target).prop('selected', false);
                }
            });
        });
    </script>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletter_list.html
{% extends 'base.html' %}

{% block title %}
    Список рассылок
{% endblock %}

{% block header %}
    Рассылки
{% endblock %}

{% block content %}
    {% if object_list %}
        <table class="table table-striped table-hover caption-top">
            <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Время рассылки</th>
                <th scope="col">Периодичность</th>
                <th scope="col">Статус рассылки</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'app_newsletter:newsletter_detail' pk=object.pk %}">{{ object.pk }}</a>
                    </td>
                    <td>{{ object.time }}</td>
                    <td>{{ object.get_frequency_display }}</td>
                    <td>{{ object.get_status_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'app_newsletter/includes/paginator.html' %}
    {% else %}
        <h3>Пока здесь пусто</h3>
    {% endif %}
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletterlog_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object }}
{% endblock %}

{% block header %}
    {{ object }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h5>Время:</h5>
            <p>{{ object.date_time|date:"D d M Y" }} {{ object.date_time|time:"H:i:s" }}</p>
            <h5>Статус:</h5>
            <p>{{ object.get_status_display }}</p>
            <h5>Ответ сервера:</h5>
            <p>{{ object.server_response }}</p>
            <h5>Клиент:</h5>
            <p>{{ object.client.email }} ({{ object.client.first_name }} {{ object.client.last_name }})</p>
            <h5>Заголовок письма:</h5>
            <p>{{ object.message.subject }}</p>
            <h5>Тело письма:</h5>
            <p>{{ object.message.body }}</p>
            <h5>Рассылка:</h5>
            {% if object.newsletter %}
                <p>
                    <a href="{% url 'app_newsletter:newsletter_detail' pk=object.newsletter.pk %}">
                        {{ object.newsletter }}
                    </a>
                </p>
            {% else %}
                <p>Рассылка удалена</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

sky_store/app_newsletter/templates/app_newsletter/newsletterlog_list.html
{% extends 'base.html' %}

{% block title %}
    Журнал рассылок
{% endblock %}

{% block header %}
    Журнал рассылок
{% endblock %}

{% block content %}
    {% if object_list %}
        <table class="table table-striped table-hover caption-top">
            <thead>
            <tr>
                <th scope="col">Дата лога</th>
                <th scope="col">Статус</th>
                <th scope="col">Ответ сервера</th>
                <th scope="col">Получатель</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'app_newsletter:newsletter_log_detail' pk=object.pk %}">
                            {{ object.date_time|date:"D d M Y" }} {{ object.date_time|time:"H:i:s" }}
                        </a>
                    </td>
                    <td>{{ object.get_status_display }}</td>
                    <td>{{ object.server_response }}</td>
                    <td>{{ object.client.email }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'app_newsletter/includes/paginator.html' %}
    {% else %}
        <h3>Пока здесь пусто</h3>
    {% endif %}
{% endblock %}