sky_store/app_blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from .apps import AppBlogConfig
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = AppBlogConfig.name

urlpatterns = [
    path('posts/', PostListView.as_view(), name='post_list'),
    path('post/create/', never_cache(PostCreateView.as_view()), name='post_create'),
    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
]

sky_store/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_catalog.urls', namespace='app_catalog')),
    path('', include('app_blog.urls', namespace='app_blog')),
    path('', include('app_newsletter.urls', namespace='app_newsletter')),
    path('user/', include('app_user.urls', namespace='app_user'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_store/app_blog/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models

from app_user.models import CustomUser


class Post(models.Model):
    """
    Модель, описывающая пост в блоге
    """
    title = models.CharField(max_length=255, unique=True, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, blank=True, verbose_name='URL')
    content = models.TextField(verbose_name='Содержание')
    preview = models.ImageField(upload_to='posts/', verbose_name='Изображение (превью)', default='posts/default.jpg')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(verbose_name='Опубликован', default=True)
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    created_by = models.ForeignKey(CustomUser, on_delete=models.SET_DEFAULT, default=1, verbose_name='Кем создан')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        db_table = 'posts'
        ordering = ['created_at']

    def __str__(self):
        return self.title

    def increment_view_count(self):
        """
        Увеличивает счетчик просмотров поста на 1.
        Если счетчик просмотров достигает 100, отправляет
        письмо на электронную почту.
        """
        self.views_count += 1
        self.save()

        if self.views_count == 100:
            send_mail(
                subject='Поздравляем с достижением!',
                message=f'Статья "{self.title}" достигла 100 просмотров!',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER]
            )

    def make_unpublished(self):
        """
        Помечает пост как неопубликованный.
        """
        self.published = False
        self.save()

sky_store/app_blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'preview']
        labels = {
            'title': 'Заголовок',
            'content': 'Содержание',
            'preview': 'Изображение (превью)',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите текст статьи'}),
            'preview': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        }

sky_store/app_blog/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from slugify import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from permissions.authenticate import AuthenticatedAccessMixin
from permissions.user_permission import CombinedAccessMixin
from .forms import PostCreateForm
from .models import Post


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)
        return queryset


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.increment_view_count()
        return obj


class PostCreateView(AuthenticatedAccessMixin, CreateView):
    model = Post
    form_class = PostCreateForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.slug = slugify(post.title)
        post.save()
        messages.success(request=self.request, message='Статья успешно создана')
        return redirect(reverse('app_blog:post_detail', kwargs={'slug': post.slug}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Создать'
        return context


class PostUpdateView(CombinedAccessMixin, UpdateView):
    model = Post
    form_class = PostCreateForm

    def form_valid(self, form):
        post = form.save()
        post.slug = slugify(post.title)
        post.save()
        messages.success(request=self.request, message='Статья успешно отредактирована')
        return redirect(reverse('app_blog:post_detail', kwargs={'slug': post.slug}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Редактировать'
        return context


class PostDeleteView(CombinedAccessMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('app_blog:post_list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.make_unpublished()

        message = f'Статус статьи "{self.object.title}" изменён на не опубликована'
        messages.success(request, message)

        return HttpResponseRedirect(self.get_success_url())

sky_store/app_blog/templates/app_blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить пост
{% endblock %}

{% block header %}
    Удалить пост
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <p>Уверены, что хотите удалить пост "{{ object.title }}"?</p>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
    </form>
{% endblock %}

sky_store/app_blog/templates/app_blog/post_detail.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block header %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <p><b>Дата: </b>{{ object.created_at }}</p>
            <p><b>Количество просмотров: </b>{{ object.views_count }}</p>
            <p>{{ object.content }}</p>
        </div>
    </div>
    <div class="row">
        {% if request.user == object.created_by or request.user|has_group:"Контент менеджеры" %}
        <div class="col-lg-12 d-flex justify-content-between">
            <div>
                <a href="{% url 'app_blog:post_update' slug=object.slug %}" class="btn btn-warning m-4"
                   role="button">
                    Редактировать пост
                </a>
            </div>
            <div>
                <a href="{% url 'app_blog:post_delete' slug=object.slug %}" class="btn btn-danger m-4"
                   role="button">
                    Удалить пост
                </a>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

sky_store/app_blog/templates/app_blog/post_form.html
{% extends 'base.html' %}

{% block title %}
    {{ action }} пост
{% endblock %}

{% block header %}
    {{ action }} пост
{% endblock %}

{% block content %}

    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="{{ action }}">
    </form>
{% endblock %}

sky_store/app_blog/templates/app_blog/post_list.html
{% extends 'base.html' %}

{% block title %}
    Публикации
{% endblock %}

{% block header %}
    Публикации
{% endblock %}

{% block content %}
    {% if object_list %}
        <div class="row">
            {% for object in object_list %}
                {% include 'app_blog/includes/post_card.html' %}
            {% endfor %}
        </div>
    {% else %}
        <h3>Пока здесь пусто</h3>
    {% endif %}
{% endblock %}