sky_store/app_blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from .apps import AppBlogConfig
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = AppBlogConfig.name

urlpatterns = [
    path('posts/', PostListView.as_view(), name='post_list'),
    path('post/create/', never_cache(PostCreateView.as_view()), name='post_create'),
    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
]

sky_store/app_catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from .apps import AppConfig
from .views import (
    HomePageView,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactsView,
    SuccessFeedbackView,
    UserProductListView,
    UnpublishedProductListView
)

app_name = AppConfig.__name__

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('user/products/', UserProductListView.as_view(), name='user_products'),
    path('products/unpublished/', UnpublishedProductListView.as_view(), name='unpublished_products'),
    path('product/<int:pk>/', cache_page(60 * 2)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('contacts/success-feedback', SuccessFeedbackView.as_view(), name='success_feedback')
]

sky_store/app_newsletter/urls.py
from django.urls import path

from .apps import AppNewsletterConfig
from .views import (
    ClientCreateView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
    NewsletterListView,
    NewsletterDetailView,
    NewsletterCreateView,
    NewsletterUpdateView,
    NewsletterDeleteView,
    NewsletterLogListView,
    NewsletterLogDetailView
)

app_name = AppNewsletterConfig.name

urlpatterns = [
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='newsletter_create'),
    path('newsletter/update/<int:pk>/', NewsletterUpdateView.as_view(), name='newsletter_update'),
    path('newsletter/delete/<int:pk>/', NewsletterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletterlogs/', NewsletterLogListView.as_view(), name='newsletter_log_list'),
    path('newsletterlogs/<int:pk>/', NewsletterLogDetailView.as_view(), name='newsletter_log_detail'),
]

sky_store/app_user/urls.py
from django.urls import path

from .apps import AppUserConfig
from .views import (
    UserRegisterView,
    EmailConfirmationView,
    UserLoginView,
    logout_user,
    UserUpdateView,
    UserDetailView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    UserListView
)

app_name = AppUserConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('confirm-email/<str:uidb64>/<str:token>/', EmailConfirmationView.as_view(), name='confirm_email'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('profile/update/', UserUpdateView.as_view(), name='profile_update'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('all/', UserListView.as_view(), name='user_list')
]

sky_store/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_catalog.urls', namespace='app_catalog')),
    path('', include('app_blog.urls', namespace='app_blog')),
    path('', include('app_newsletter.urls', namespace='app_newsletter')),
    path('user/', include('app_user.urls', namespace='app_user'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_store/templates/includes/footer.html
<footer>
	<section class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-6">
					<h4>SkyStore</h4>
					<small class="d-block mb-3 text-muted">&copy; 2023</small>
				</div>
				<div class="col-md-4 col-6">
					<h4>Магазин</h4>
					<ul class="list-unstyled">
						<ul class="list-unstyled">
							<li>
								<a href="{% url 'app_catalog:product_list' %}">Каталог</a>
							</li>
							<li>
								<a href="{% url 'app_catalog:create_product' %}">Добавить товар</a>
							</li>
						</ul>
					</ul>
				</div>
				<div class="col-md-4 col-6">
					<h4>О нас</h4>
					<ul class="list-unstyled">
						<li>
							<a href="{% url 'app_catalog:contacts' %}">Контакты</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
</footer>

sky_store/templates/includes/navigation.html
{% load user_filters %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app_catalog:home' %}">SkyStore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto top-menu">
            {% if request.resolver_match.url_name == 'product_list' %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="categoryDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Категории
                    </a>
                    <div class="dropdown-menu" aria-labelledby="categoryDropdown">
                        <a class="dropdown-item" href="{% url 'app_catalog:product_list' %}">Все</a>
                        <div class="dropdown-divider"></div>
                        {% for category in categories %}
                            <a class="dropdown-item"
                               href="{% url 'app_catalog:product_list' %}?{% if request.GET.page %}page={{ request.GET.page }}&{% endif %}category={{ category.id }}">
                                {{ category.name }}
                            </a>
                        {% endfor %}
                    </div>
                </li>
            {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="catalogDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Каталог
                    </a>
                    <div class="dropdown-menu" aria-labelledby="catalogDropdown">
                        <a class="dropdown-item" href="{% url 'app_catalog:product_list' %}">Все товары</a>
                        {% if request.user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'app_catalog:create_product' %}">Добавить товар</a>
                        <a class="dropdown-item" href="{% url 'app_catalog:user_products' %}">Созданные мной</a>
                        {% endif %}
                    </div>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_catalog:contacts' %}">Контакты</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="blogDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Блог
                </a>
                <div class="dropdown-menu" aria-labelledby="blogDropdown">
                    <a class="dropdown-item" href="{% url 'app_blog:post_list' %}">Статьи</a>
                    {% if request.user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'app_blog:post_create' %}">Создать статью</a>
                    {% endif %}
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="newsletterDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Рассылки
                </a>
                <div class="dropdown-menu" aria-labelledby="newsletterDropdown">
                    <a class="dropdown-item" href="{% url 'app_newsletter:client_list' %}">Список клиентов</a>
                    <a class="dropdown-item" href="{% url 'app_newsletter:newsletter_list' %}">Список рассылок</a>
                    <a class="dropdown-item" href="{% url 'app_newsletter:client_create' %}">Создать клиента</a>
                    <a class="dropdown-item" href="{% url 'app_newsletter:newsletter_create' %}">Создать рассылку</a>
                    <a class="dropdown-item" href="{% url 'app_newsletter:newsletter_log_list' %}">Отчёт по проведённым
                        рассылкам</a>
                </div>
            </li>
            {% if request.user.is_superuser %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'app_user:user_list' %}">Управление пользователями</a>
            </li>
            {% endif %}
            {% if request.user|has_group:"Модераторы" %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'app_catalog:unpublished_products' %}">Неопубликованные товары</a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ms-auto mb-2 top-menu">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="blogDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-regular fa-user"></i>
                    {% if request.user.is_authenticated %}
                        {{ request.user }}
                    {% endif %}
                </a>
                {% if request.user.is_authenticated %}
                    <ul class="dropdown-menu user-dropdown-menu" aria-labelledby="blogDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'app_user:profile' pk=request.user.pk %}">
                                {{ request.user }}
                            </a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'app_user:logout' %}">Выход</a></li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu user-dropdown-menu" aria-labelledby="blogDropdown">
                        <li><a class="dropdown-item" href="{% url 'app_user:register' %}">Регистрация</a></li>
                        <li><a class="dropdown-item" href="{% url 'app_user:login' %}">Авторизация</a></li>
                    </ul>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

sky_store/templates/includes/paginator.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>