sky_store/app_user/urls.py
from django.urls import path

from .apps import AppUserConfig
from .views import (
    UserRegisterView,
    EmailConfirmationView,
    UserLoginView,
    logout_user,
    UserUpdateView,
    UserDetailView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    UserListView
)

app_name = AppUserConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('confirm-email/<str:uidb64>/<str:token>/', EmailConfirmationView.as_view(), name='confirm_email'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('profile/update/', UserUpdateView.as_view(), name='profile_update'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('all/', UserListView.as_view(), name='user_list')
]

sky_store/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_catalog.urls', namespace='app_catalog')),
    path('', include('app_blog.urls', namespace='app_blog')),
    path('', include('app_newsletter.urls', namespace='app_newsletter')),
    path('user/', include('app_user.urls', namespace='app_user'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_store/app_user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from .managers import CustomUserManager

NULLABLE = {'blank': True, 'null': True}


class CustomUser(AbstractUser):
    """
    Модель, описывающая пользователя сервиса рассылок.
    Наследуется от AbstractUser.
    """
    objects = CustomUserManager()

    username = None
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    email_verified = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', default='users/default.png')
    phone = models.CharField(max_length=15, verbose_name='Телефон')
    country = models.CharField(max_length=100, verbose_name='Страна')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        db_table = 'users'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @classmethod
    def get_user_by_id(cls, user_id: int) -> 'CustomUser':
        """
        Возвращает пользователя по его идентификатору.

        :param user_id: Идентификатор пользователя.
        :return: Объект пользователя с указанным идентификатором.
        """
        return cls.objects.get(id=user_id)

    @classmethod
    def get_user_by_email(cls, user_email: str) -> 'CustomUser':
        """
        Возвращает пользователя по его электронной почте.

        :param user_email: Электронная почта пользователя.
        :return: Объект пользователя с указанной электронной почтой.
        """
        return cls.objects.get(email=user_email)

    def get_absolute_url(self) -> str:
        """
        Возвращает абсолютный URL профиля пользователя.

        Используется в Django представлениях (например, в UpdateView)
        для автоматического определения URL-адреса перенаправления
        после успешного обновления экземпляра модели.
        """
        return reverse('app_user:profile', args=[str(self.id)])

sky_store/app_user/views.py
import logging
from typing import Dict, Any

from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.models import Group
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.db.models import QuerySet
from django.forms import Form
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, ListView

from permissions.authenticate import AuthenticatedAccessMixin
from permissions.user_permission import AdminAccessMixin
from .forms import UserRegistrationForm, UserLoginForm, UserUpdateForm, CustomPasswordResetForm, CustomSetPasswordForm
from .models import CustomUser
from .services import EmailConfirmationService, email_token_generator

logger = logging.getLogger(__name__)


class UserRegisterView(CreateView):
    """
    Представление для регистрации пользователя.
    Наследуется от CreateView для создания нового экземпляра пользователя.
    После успешной валидации формы, отправляет письмо с подтверждением на email пользователя.
    """
    model = CustomUser
    form_class = UserRegistrationForm
    success_url = reverse_lazy('app_catalog:home')

    def form_valid(self, form: Form) -> HttpResponseRedirect:
        """
        Метод вызывается, если форма валидна.
        Создает и сохраняет пользователя, отправляет письмо с подтверждением.
        :param form: Валидная форма.
        """
        user = form.save(commit=False)
        user.is_active = False
        user.username = user.email
        user.save()

        EmailConfirmationService.send_confirmation_email(user=user, request=self.request)

        messages.success(self.request, 'Спасибо за регистрацию! Вам на почту выслано письмо с подтверждением.')

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Возвращает контекстные данные для шаблона
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        context['header'] = 'Регистрация'
        context['action'] = 'Зарегистрироваться'
        return context


class EmailConfirmationView(View):
    """
    Представление для подтверждения email пользователя.
    При GET запросе проверяет токен и активирует аккаунт пользователя.
    """

    def get(self, request: HttpRequest, uidb64: str, token: str) -> HttpResponseRedirect:
        """
        При получении GET запроса декодирует id пользователя, проверяет токен и активирует аккаунт пользователя.
        Если токен невалидный или пользователь не найден, возвращает ошибку.
        :param request: HttpRequest объект.
        :param uidb64: Закодированный id пользователя.
        :param token: Токен для проверки.
        """
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = CustomUser.get_user_by_id(user_id=uid)

            logger.debug('Старт процедуры подтверждения email')
            logger.debug(f"Получено из URL user.id = {user.pk}, {user}")
            logger.debug(f"Получено из URL token: {token}")

            if email_token_generator.check_token(user=user, token=token):
                logger.debug('Получен корректный токен')
                user.email_verified = True
                user.is_active = True
                user.save()
                login(request=request, user=user)
                messages.success(request=self.request, message='Регистрация на сайте успешно завершена!')
                return redirect(user.get_absolute_url())

            else:
                logger.debug('Получен некорректный токен')
                messages.error(
                    request=self.request,
                    message='Ваш email не подтверждён! '
                            'Пожалуйста, проверьте вашу почту и следуйте инструкциям '
                            'для подтверждения электронной почты.'
                )
                return HttpResponseRedirect(user.get_absolute_url())
        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            messages.error(
                request=self.request,
                message='Ваш email не подтверждён! '
                        'Пожалуйста, проверьте вашу почту и следуйте инструкциям '
                        'для подтверждения электронной почты.'
            )
            return redirect(to='app_catalog:home')


class UserLoginView(LoginView):
    """
    Представление для входа пользователя в систему.
    Наследуется от стандартного Django LoginView.
    Использует UserLoginForm как форму входа и
    отображает эту форму на странице 'app_user/login.html'.
    """
    form_class = UserLoginForm
    template_name = 'app_user/login.html'

    def form_invalid(self, form: UserLoginForm) -> HttpResponse:
        """
        Метод вызывается, если форма недействительна.
        В этом методе происходит проверка подтверждён ли адрес электронной почты,
        заблокирован ли пользователь, существует ли такой адрес электронной почты в системе,
        корректный ли пароль.
        В зависимости от ошибки выводятся соответствующие сообщения об ошибках.
        :param form: Форма, которая не прошла валидацию.
        """
        email = form.data.get('username')

        try:
            user = CustomUser.get_user_by_email(user_email=email)

            if not user.email_verified:
                logger.debug('Попытка логина с неподтверждённой почтой')
                message = 'Ваш email не подтвержден. ' \
                          'Пожалуйста, перейдите по ссылке, отправленной на вашу электронную почту!'
                messages.error(self.request, message=message)
                return redirect(to='app_catalog:home')

        except CustomUser.DoesNotExist:
            logger.debug(f'Пользователь с почтой {form.data.get("username")} не найден')
            message = 'Пользователь с таким адресом электронной почты не найден! ' \
                      'Введите корректный адрес электронной почты или ' \
                      'пройдите регистрацию на нашем сайте, если вы здесь впервые.'
            messages.error(self.request, message=message)
            return redirect(to='app_user:login')

        if form.errors.get('__all__'):
            message = 'Вы ввели неверный пароль!'
            messages.error(self.request, message=message)
            return super().form_invalid(form)

        return super().form_invalid(form)

    def get_success_url(self) -> str:
        """
        Метод возвращает URL-адрес, на который будет перенаправлен
        клиент после успешного входа.
        """
        return self.request.user.get_absolute_url()


def logout_user(request: HttpRequest) -> HttpResponseRedirect:
    """
    Представление для выхода пользователя из системы и
    перенаправление на страницу входа.
    """
    logout(request)
    return redirect(to='app_user:login')


class UserUpdateView(AuthenticatedAccessMixin, UpdateView):
    """
    Представление для редактирования профиля пользователя
    """
    model = CustomUser
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        """
        Метод для получения объекта пользователя, который будет редактироваться.
        В данном случае, используется текущий пользователь.
        """
        return self.request.user

    def form_valid(self, form):
        """
        Метод, вызываемый при валидной форме.
        В данном случае, сохраняет изменения и выполняет редирект.
        """
        response = super().form_valid(form)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        """
        Возвращает контекстные данные для шаблона
        """
        context = super().get_context_data(**kwargs)
        context['title'] = f'Профиль | {self.request.user}'
        context['header'] = self.request.user
        context['action'] = 'Сохранить'
        return context


class UserDetailView(AuthenticatedAccessMixin, DetailView):
    """
    Представление для отображения детальной информации о пользователе
    """
    model = CustomUser


class CustomPasswordResetView(PasswordResetView):
    """
    Представление для сброса пароля.
    Наследуется от Django PasswordResetView.
    """
    email_template_name = 'app_user/password_reset_email.html'
    template_name = 'app_user/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('app_user:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    """
    Представление для отображения страницы успешной отправки
    ссылки на сброс пароля.
    Наследуется от Django PasswordResetDoneView.
    """
    template_name = 'app_user/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Представление для отображения страницы подтверждения сброса пароля.
    Наследуется от Django PasswordResetConfirmView.
    """
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy("app_user:password_reset_complete")
    template_name = "app_user/password_reset_confirm.html"


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    """
    Представление для отображения страницы успешного сброса пароля.
    Наследуется от Django PasswordResetCompleteView.
    """
    template_name = 'app_user/password_reset_complete.html'


class UserListView(AdminAccessMixin, ListView):
    """
    Представление для отображения списка пользователей сервиса.
    Наследуется от AdminAccessMixin и Django-класса ListView.
    Класс AdminAccessMixin обеспечивает доступ к представлению
    только для администраторов.

sky_store/app_user/templates/app_user/confirmation_email.html
{% autoescape off %}
    Здравствуйте, {{ user.first_name }} {{ user.last_name }}!

    Для завершения регистрации на нашем сайте, пожалуйста, перейдите по следующей ссылке:
    http://{{ domain }}{% url 'app_user:confirm_email' uidb64=uid token=token %}

    Если вы не регистрировались на нашем сайте, проигнорируйте это сообщение.
{% endautoescape %}

sky_store/app_user/templates/app_user/customuser_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ header }}
{% endblock %}


{% block content %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-10 mt-5 pt-5">
            <div class="row z-depth-3">
                <div class="col-sm-4 rounded-left">
                    <div class="card-block text-center">
                        <img src="{{ user.avatar.url }}"
                             class="img-thumbnail">
                        <p><a href="{% url 'app_user:profile_update' %}">Редактировать профиль</a></p>
                    </div>
                </div>
                <div class="col-sm-8 bg-white rounded-right">
                    <h3 class="mt-3 text-center">{{ request.user }}</h3>
                    <hr class="badge-primary">
                    <div class="row">
                        <div class="col">
                            <p>
                                <strong>Имя: </strong> {% firstof request.user.first_name '-' %}
                            </p>
                            <p>
                                <strong>Фамилия: </strong> {% firstof request.user.last_name '-' %}
                            </p>
                            <p>
                                <strong>E-mail: </strong> {% firstof request.user.email '-' %}
                            </p>
                            <p>
                                <strong>Телефон: </strong> {% firstof request.user.phone '-' %}
                            </p>
                            <p>
                                <strong>Страна: </strong> {% firstof request.user.country '-' %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sky_store/app_user/templates/app_user/customuser_form.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ header }}
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="{{ action }}">
    </form>
{% endblock %}

sky_store/app_user/templates/app_user/customuser_list.html
{% extends 'base.html' %}

{% block title %}
    Пользователи сервиса
{% endblock %}

{% block header %}
    Список пользователей
{% endblock %}

{% block content %}
    {% if object_list %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-striped table-hover caption-top">
                <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Электронная почта</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Сделать модератором</th>
                    <th scope="col">Сделать контент менеджером</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ object.id }}</th>
                        <th>{{ object.email }}</th>
                        <td>{{ object.first_name }}</td>
                        <td>{{ object.last_name }}</td>
                        <td>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input"
                                       {% if object.id in moderator_ids %}checked{% endif %}
                                       value="{{ object.pk }}" name="box_moderator">
                            </div>
                        </td>
                        <td>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input"
                                       {% if object.id in content_manager_ids %}checked{% endif %}
                                       value="{{ object.pk }}" name="box_content_manager">
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <button type="submit" class="btn btn-success">Применить</button>
        </form>
        {% include 'includes/paginator.html' %}
    {% else %}
        <h3>Пока здесь пусто</h3>
    {% endif %}
{% endblock %}

sky_store/app_user/templates/app_user/login.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block header %}
    Авторизация
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="d-flex justify-content-between align-items-center">
            <input type="submit" class="btn btn-success" value="Войти">
            <a href="{% url 'app_user:password_reset' %}" class="btn btn-warning">Забыл пароль</a>
        </div>
    </form>
{% endblock %}

sky_store/app_user/templates/app_user/password_reset_complete.html
{% extends "base.html" %}

{% block title %}
    Пароль восстановлен
{% endblock %}

{% block header %}
    Пароль восстановлен
{% endblock %}

{% block content %}
    <p>Ваш новый пароль установлен. Вы можете <a href="{% url 'app_user:login' %}"
                                                 style="color: green">авторизоваться</a></p>
{% endblock %}

sky_store/app_user/templates/app_user/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}
    Восстановление пароля
{% endblock %}

{% block header %}
    Восстановление пароля
{% endblock %}

{% block content %}
    {% if validlink %}
        <p>Пожалуйста, введите ваш новый пароль два раза:</p>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% for error in field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-success" value="Установить новый пароль">
        </form>
    {% else %}
        <p>Ссылка для сброса пароля недействительна. Вероятно она
            уже была использована. Пожалуйста, запросите восстановление пароля еще раз.</p>
    {% endif %}
{% endblock %}

sky_store/app_user/templates/app_user/password_reset_done.html
{% extends "base.html" %}

{% block title %}
    Сброс пароля
{% endblock %}

{% block header %}
    Сброс пароля
{% endblock %}

{% block content %}
  <p>
    Ссылка для восстановления пароля отправлена на указанный адрес.
  </p>
  <p>
    Если вы не получили письмо, убедитесь, что введен адрес электронной почты,
      который был указан при регистрации. Проверьте папку со спамом.
  </p>
{% endblock %}

sky_store/app_user/templates/app_user/password_reset_email.html
{% autoescape off %}
    Здравствуйте, {{ user.first_name }} {{ user.last_name }}!

    Вы получили это письмо, потому что кто-то запросил сброс пароля для вашего аккаунта на сайте.
    Пожалуйста, перейдите по ссылке ниже для сброса пароля:
    http://{{ domain }}{% url 'app_user:password_reset_confirm' uidb64=uid token=token %}

{% endautoescape %}

sky_store/app_user/templates/app_user/password_reset_form.html
{% extends 'base.html' %}

{% block title %}
    Восстановление пароля
{% endblock %}

{% block header %}
    Забыли ваш пароль?
{% endblock %}

{% block content %}
    <p>Введите свой адрес электронной почты, чтобы получить новый пароль</p>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="Отправить">
    </form>
{% endblock %}